info:
  application:
    description: ${description}
    name: ${rootProject.name}
    version: ${version}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,logfile,flyway,env
